# Generated by Django 5.2.16 on 2026-07-24 05:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(editable=False, help_text='Tự sinh: GRN-YYYYMM-XXX.', max_length=30, unique=True)),
                ('grn_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('actual_arrival_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING_QC', 'Chờ QC'), ('QC_IN_PROGRESS', 'Đang QC'), ('RECEIVED', 'Đã nhận'), ('REJECTED', 'Từ chối'), ('CLOSED', 'Đã đóng')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns_created', to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='partners.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Ngày sản xuất')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng')),
                ('batch_code', models.CharField(blank=True, help_text='Mã lô từ NCC.', max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Chờ nhận'), ('RECEIVED', 'Đã nhận'), ('PARTIAL_RECEIVED', 'Nhận một phần'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.grn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='GrnReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='QC Fail')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('APPROVED', 'Đã duyệt'), ('RETURNED', 'Đã trả hàng'), ('CLOSED', 'Đã đóng')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='receiving.grn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
