# Generated by Django 5.2.16 on 2026-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='qty_pass',
            field=models.PositiveIntegerField(blank=True, help_text='Số lượng đạt QC — null nghĩa là chưa QC (mục 2c).', null=True),
        ),
    ]
