# Generated by Django 5.2.16 on 2026-07-25 14:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_alter_product_category_and_more'),
        ('partners', '0004_alter_supplier_options_alter_supplier_contact_email_and_more'),
        ('purchasing', '0004_alter_purchaseorder_options_and_more'),
        ('receiving', '0002_grnitem_qty_pass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiếu nhập kho', 'verbose_name_plural': 'Phiếu nhập kho'},
        ),
        migrations.AlterModelOptions(
            name='grnitem',
            options={'verbose_name': 'Dòng phiếu nhập kho', 'verbose_name_plural': 'Dòng phiếu nhập kho'},
        ),
        migrations.AlterModelOptions(
            name='grnreturn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiếu trả hàng NCC', 'verbose_name_plural': 'Phiếu trả hàng NCC'},
        ),
        migrations.AlterField(
            model_name='grn',
            name='actual_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày nhận thực tế'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến nhận'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='grn_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày lập phiếu'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='grn_no',
            field=models.CharField(editable=False, help_text='Tự sinh: GRN-YYYYMM-XXX.', max_length=30, unique=True, verbose_name='Số phiếu GRN'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchasing.purchaseorder', verbose_name='Đơn mua hàng'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING_QC', 'Chờ QC'), ('QC_IN_PROGRESS', 'Đang QC'), ('RECEIVED', 'Đã nhận'), ('REJECTED', 'Từ chối'), ('CLOSED', 'Đã đóng')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='partners.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='batch_code',
            field=models.CharField(blank=True, help_text='Mã lô từ NCC.', max_length=40, verbose_name='Mã lô NCC'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.grn', verbose_name='Phiếu GRN'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='qty_ordered',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng đặt'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='qty_pass',
            field=models.PositiveIntegerField(blank=True, help_text='Số lượng đạt QC — null nghĩa là chưa QC (mục 2c).', null=True, verbose_name='Số lượng đạt QC'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='qty_received',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng nhận'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ nhận'), ('RECEIVED', 'Đã nhận'), ('PARTIAL_RECEIVED', 'Nhận một phần'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='grnreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='grnreturn',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='receiving.grn', verbose_name='Phiếu GRN'),
        ),
        migrations.AlterField(
            model_name='grnreturn',
            name='reason',
            field=models.TextField(default='QC Fail', verbose_name='Lý do trả hàng'),
        ),
        migrations.AlterField(
            model_name='grnreturn',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('APPROVED', 'Đã duyệt'), ('RETURNED', 'Đã trả hàng'), ('CLOSED', 'Đã đóng')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
