# Generated by Django 5.2 on 2026-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0003_alter_grn_options_alter_grnitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING_APPROVAL', 'Chờ duyệt nộp'), ('PENDING_QC', 'Chờ QC'), ('QC_IN_PROGRESS', 'Đang QC'), ('RECEIVED', 'Đã nhận'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy'), ('CLOSED', 'Đã đóng')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
