# Generated by Django 5.2.16 on 2026-08-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_warehousehandoff_status'),
        ('receiving', '0004_alter_grn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnreturn',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Null = return legacy FULL-fail (bao phủ mọi lô SCRAP của GRN). Non-null = return gắn đúng 1 lô QUARANTINE (disposition / PARTIAL).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.batch', verbose_name='Lô Quarantine'),
        ),
        migrations.AddField(
            model_name='grnreturn',
            name='qty',
            field=models.PositiveIntegerField(blank=True, help_text='Bắt buộc khi có batch; null khi return legacy không gắn lô.', null=True, verbose_name='Số lượng trả'),
        ),
    ]
