# Generated by Django 5.2.16 on 2026-07-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(help_text='Mã NCC, vd NCC-0001.', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, help_text='SĐT/email/người liên hệ.', max_length=200)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Thời gian giao hàng dự kiến (ngày) — dùng cho FR-PO-05.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['supplier_code'],
            },
        ),
    ]
