# Generated by Django 5.2 on 2026-07-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='qty_tolerance_percent',
            field=models.PositiveIntegerField(default=5, help_text='Ngưỡng % chênh lệch Qty nhận thực tế so với Qty đặt trước khi GRN cảnh báo (FR-GRN-07).'),
        ),
    ]
