# Generated by Django 5.2 on 2026-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_supplier_qty_tolerance_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Họ tên người liên hệ.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_title',
            field=models.CharField(blank=True, help_text='Chức vụ.', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hạn mức công nợ tối đa.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('VND', 'VND'), ('USD', 'USD'), ('EUR', 'EUR'), ('OTHER', 'Khác')], default='VND', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Địa chỉ kho/giao hàng thực tế, nếu khác trụ sở chính.', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Ghi chú nội bộ (đánh giá, lưu ý đặc biệt...).'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='international_name',
            field=models.CharField(blank=True, help_text='Tên quốc tế/viết tắt dùng để in chứng từ.', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Điều khoản thanh toán (vd: Công nợ 30 ngày).', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registered_address',
            field=models.CharField(blank=True, help_text='Địa chỉ đăng ký kinh doanh.', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Ngừng giao dịch'), ('SUSPENDED', 'Tạm khóa')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_group',
            field=models.CharField(blank=True, help_text='Nhóm NCC (vd: vật tư phụ trợ, dịch vụ bảo trì, nhà thầu phụ...).', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Mã số thuế.', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
