# Generated by Django 5.2.16 on 2026-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_remove_supplier_contact_remove_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['supplier_code'], 'verbose_name': 'Nhà cung cấp', 'verbose_name_plural': 'Nhà cung cấp'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email liên hệ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Họ tên người liên hệ.', max_length=150, verbose_name='Người liên hệ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_title',
            field=models.CharField(blank=True, help_text='Chức vụ.', max_length=100, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hạn mức công nợ tối đa.', max_digits=14, null=True, verbose_name='Hạn mức công nợ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('VND', 'VND'), ('USD', 'USD'), ('EUR', 'EUR'), ('OTHER', 'Khác')], default='VND', max_length=10, verbose_name='Đơn vị tiền tệ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Địa chỉ kho/giao hàng thực tế, nếu khác trụ sở chính.', max_length=255, verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Ghi chú nội bộ (đánh giá, lưu ý đặc biệt...).', verbose_name='Ghi chú nội bộ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='international_name',
            field=models.CharField(blank=True, help_text='Tên quốc tế/viết tắt dùng để in chứng từ.', max_length=200, verbose_name='Tên quốc tế'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Thời gian giao hàng dự kiến (ngày) — dùng cho FR-PO-05.', null=True, verbose_name='Thời gian giao hàng (ngày)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Điều khoản thanh toán (vd: Công nợ 30 ngày).', max_length=200, verbose_name='Điều khoản thanh toán'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='qty_tolerance_percent',
            field=models.PositiveIntegerField(default=5, help_text='Ngưỡng % chênh lệch Qty nhận thực tế so với Qty đặt trước khi GRN cảnh báo (FR-GRN-07).', verbose_name='Ngưỡng chênh lệch Qty (%)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='registered_address',
            field=models.CharField(blank=True, help_text='Địa chỉ đăng ký kinh doanh.', max_length=255, verbose_name='Địa chỉ đăng ký'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Ngừng giao dịch'), ('SUSPENDED', 'Tạm khóa')], default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(help_text='Mã NCC, vd NCC-0001.', max_length=30, unique=True, verbose_name='Mã NCC'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_group',
            field=models.CharField(blank=True, help_text='Nhóm NCC (vd: vật tư phụ trợ, dịch vụ bảo trì, nhà thầu phụ...).', max_length=100, verbose_name='Nhóm NCC'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Mã số thuế.', max_length=20, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
