# Generated by Django 5.2 on 2026-07-26 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_supplier_options_alter_supplier_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Nhân viên mua hàng đã tạo NCC này — chỉ người này (hoặc Manager/Admin) được sửa. Tự gán khi tạo, không sửa tay qua form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý'),
        ),
    ]
