# Generated by Django 5.2.16 on 2026-07-24 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã kho, vd KHO-HN.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Dung tích kho (đơn vị tuỳ chọn, vd m3/pallet).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã vị trí, vd Giá-A-01.', max_length=30)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['warehouse__code', 'code'],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_location_code_per_warehouse')],
            },
        ),
    ]
