# Generated by Django 5.2 on 2026-07-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('MAIN', 'Kho thành phẩm'), ('STAGING', 'Kho chờ'), ('SCRAP', 'Kho phế')], default='MAIN', help_text='MAIN: kho thường (GIN/FIFO được phép xuất). STAGING/SCRAP: kho hệ thống, tối đa 1 kho hoạt động/loại.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('warehouse_type__in', ['STAGING', 'SCRAP'])), fields=('warehouse_type',), name='unique_active_staging_scrap_warehouse'),
        ),
    ]
