# Generated by Django 5.2.16 on 2026-07-25 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouse_warehouse_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['warehouse__code', 'code'], 'verbose_name': 'Vị trí lưu trữ', 'verbose_name_plural': 'Vị trí lưu trữ'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['code'], 'verbose_name': 'Kho', 'verbose_name_plural': 'Kho'},
        ),
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dung tích'),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(help_text='Mã vị trí, vd Giá-A-01.', max_length=30, verbose_name='Mã vị trí'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='warehouse.warehouse', verbose_name='Kho'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Dung tích kho (đơn vị tuỳ chọn, vd m3/pallet).', null=True, verbose_name='Dung tích'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(help_text='Mã kho, vd KHO-HN.', max_length=20, unique=True, verbose_name='Mã kho'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tên kho'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('MAIN', 'Kho thành phẩm'), ('STAGING', 'Kho chờ'), ('SCRAP', 'Kho phế')], default='MAIN', help_text='MAIN: kho thường (GIN/FIFO được phép xuất). STAGING/SCRAP: kho hệ thống, tối đa 1 kho hoạt động/loại.', max_length=20, verbose_name='Loại kho'),
        ),
    ]
