# Generated by Django 5.2 on 2026-07-25 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_location_options_alter_warehouse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='staff',
            field=models.ManyToManyField(blank=True, help_text='Nhân viên kho được gán vào kho này — dùng để chọn/mặc định người nhận khi QC bàn giao lô hàng đã PASS về kho.', related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách'),
        ),
    ]
