# Generated by Django 5.2.16 on 2026-07-24 09:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_no', models.CharField(editable=False, help_text='Tự sinh: SO-YYYYMM-XXX.', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Lập kế hoạch'), ('EXECUTION', 'Đang kiểm đếm'), ('RECONCILIATION', 'Đối soát chênh lệch'), ('ADJUSTMENT', 'Đã điều chỉnh (hoàn tất)')], default='PLANNING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='FR-SO-07: để trống = kiểm toàn kho, chọn = giới hạn theo vị trí.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_sessions', to='warehouse.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_sessions', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_system', models.IntegerField(help_text='Snapshot Inventory.qty_on_hand lúc tạo phiếu.')),
                ('qty_actual', models.IntegerField(blank=True, help_text='FR-SO-02: Qty đếm thực tế, null = chưa quét/nhập.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(blank=True, choices=[('LOSS', 'Thất thoát'), ('DAMAGE', 'Hư hỏng'), ('THEFT', 'Mất cắp'), ('COUNTING_ERROR', 'Sai sót đếm/nhập liệu trước đó'), ('EXPIRED', 'Hết hạn sử dụng')], max_length=20)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_items_counted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_items', to='catalog.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocktake.stocktakesession')),
            ],
            options={
                'ordering': ['product__product_code'],
                'constraints': [models.UniqueConstraint(fields=('session', 'product'), name='unique_stocktake_item_per_session')],
            },
        ),
    ]
