# Generated by Django 5.2.16 on 2026-07-25 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_alter_product_category_and_more'),
        ('stocktake', '0001_initial'),
        ('warehouse', '0003_alter_location_options_alter_warehouse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktakeitem',
            options={'ordering': ['product__product_code'], 'verbose_name': 'Dòng kiểm kê', 'verbose_name_plural': 'Dòng kiểm kê'},
        ),
        migrations.AlterModelOptions(
            name='stocktakesession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiếu kiểm kê', 'verbose_name_plural': 'Phiếu kiểm kê'},
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='counted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đếm'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_items_counted', to=settings.AUTH_USER_MODEL, verbose_name='Người đếm'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_items', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='qty_actual',
            field=models.IntegerField(blank=True, help_text='FR-SO-02: Qty đếm thực tế, null = chưa quét/nhập.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng thực tế'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='qty_system',
            field=models.IntegerField(help_text='Snapshot Inventory.qty_on_hand lúc tạo phiếu.', verbose_name='Số lượng hệ thống'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='reason',
            field=models.CharField(blank=True, choices=[('LOSS', 'Thất thoát'), ('DAMAGE', 'Hư hỏng'), ('THEFT', 'Mất cắp'), ('COUNTING_ERROR', 'Sai sót đếm/nhập liệu trước đó'), ('EXPIRED', 'Hết hạn sử dụng')], max_length=20, verbose_name='Lý do chênh lệch'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocktake.stocktakesession', verbose_name='Phiếu kiểm kê'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn tất'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='location',
            field=models.ForeignKey(blank=True, help_text='FR-SO-07: để trống = kiểm toàn kho, chọn = giới hạn theo vị trí.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_sessions', to='warehouse.location', verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày đối soát'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='so_no',
            field=models.CharField(editable=False, help_text='Tự sinh: SO-YYYYMM-XXX.', max_length=30, unique=True, verbose_name='Số phiếu kiểm kê'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Lập kế hoạch'), ('EXECUTION', 'Đang kiểm đếm'), ('RECONCILIATION', 'Đối soát chênh lệch'), ('ADJUSTMENT', 'Đã điều chỉnh (hoàn tất)')], default='PLANNING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_sessions', to='warehouse.warehouse', verbose_name='Kho'),
        ),
    ]
