# Generated by Django 5.2 on 2026-07-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_grn', 'Can Create GRN (phiếu nhập)'), ('can_read_grn', 'Can Read GRN (phiếu nhập)'), ('can_update_grn', 'Can Update GRN (phiếu nhập)'), ('can_delete_grn', 'Can Delete GRN (phiếu nhập)'), ('can_approve_grn', 'Can Approve GRN (phiếu nhập)'), ('can_override_grn', 'Can Override GRN (phiếu nhập)'), ('can_create_gin', 'Can Create GIN (phiếu xuất)'), ('can_read_gin', 'Can Read GIN (phiếu xuất)'), ('can_update_gin', 'Can Update GIN (phiếu xuất)'), ('can_delete_gin', 'Can Delete GIN (phiếu xuất)'), ('can_approve_gin', 'Can Approve GIN (phiếu xuất)'), ('can_override_gin', 'Can Override GIN (phiếu xuất)'), ('can_create_opname', 'Can Create Stock Opname (kiểm kê)'), ('can_read_opname', 'Can Read Stock Opname (kiểm kê)'), ('can_update_opname', 'Can Update Stock Opname (kiểm kê)'), ('can_delete_opname', 'Can Delete Stock Opname (kiểm kê)'), ('can_approve_opname', 'Can Approve Stock Opname (kiểm kê)'), ('can_override_opname', 'Can Override Stock Opname (kiểm kê)'), ('can_create_qc', 'Can Create Quality Control'), ('can_read_qc', 'Can Read Quality Control'), ('can_update_qc', 'Can Update Quality Control'), ('can_delete_qc', 'Can Delete Quality Control'), ('can_approve_qc', 'Can Approve Quality Control'), ('can_override_qc', 'Can Override Quality Control'), ('can_create_po', 'Can Create Purchase Order'), ('can_read_po', 'Can Read Purchase Order'), ('can_update_po', 'Can Update Purchase Order'), ('can_delete_po', 'Can Delete Purchase Order'), ('can_approve_po', 'Can Approve Purchase Order'), ('can_override_po', 'Can Override Purchase Order'), ('can_create_reports', 'Can Create Reports'), ('can_read_reports', 'Can Read Reports'), ('can_update_reports', 'Can Update Reports'), ('can_delete_reports', 'Can Delete Reports'), ('can_approve_reports', 'Can Approve Reports'), ('can_override_reports', 'Can Override Reports')]},
        ),
    ]
