# Generated by Django 5.2.16 on 2026-07-25 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_user_permissions_from_role'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Nhật ký hành động', 'verbose_name_plural': 'Nhật ký hành động'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_grn', 'Tạo GRN (phiếu nhập)'), ('can_read_grn', 'Xem GRN (phiếu nhập)'), ('can_update_grn', 'Sửa GRN (phiếu nhập)'), ('can_delete_grn', 'Xoá GRN (phiếu nhập)'), ('can_approve_grn', 'Duyệt GRN (phiếu nhập)'), ('can_override_grn', 'Override GRN (phiếu nhập)'), ('can_create_gin', 'Tạo GIN (phiếu xuất)'), ('can_read_gin', 'Xem GIN (phiếu xuất)'), ('can_update_gin', 'Sửa GIN (phiếu xuất)'), ('can_delete_gin', 'Xoá GIN (phiếu xuất)'), ('can_approve_gin', 'Duyệt GIN (phiếu xuất)'), ('can_override_gin', 'Override GIN (phiếu xuất)'), ('can_create_opname', 'Tạo Kiểm kê kho (Stock Opname)'), ('can_read_opname', 'Xem Kiểm kê kho (Stock Opname)'), ('can_update_opname', 'Sửa Kiểm kê kho (Stock Opname)'), ('can_delete_opname', 'Xoá Kiểm kê kho (Stock Opname)'), ('can_approve_opname', 'Duyệt Kiểm kê kho (Stock Opname)'), ('can_override_opname', 'Override Kiểm kê kho (Stock Opname)'), ('can_create_qc', 'Tạo Kiểm tra chất lượng (QC)'), ('can_read_qc', 'Xem Kiểm tra chất lượng (QC)'), ('can_update_qc', 'Sửa Kiểm tra chất lượng (QC)'), ('can_delete_qc', 'Xoá Kiểm tra chất lượng (QC)'), ('can_approve_qc', 'Duyệt Kiểm tra chất lượng (QC)'), ('can_override_qc', 'Override Kiểm tra chất lượng (QC)'), ('can_create_pr', 'Tạo Yêu cầu mua hàng (PR)'), ('can_read_pr', 'Xem Yêu cầu mua hàng (PR)'), ('can_update_pr', 'Sửa Yêu cầu mua hàng (PR)'), ('can_delete_pr', 'Xoá Yêu cầu mua hàng (PR)'), ('can_approve_pr', 'Duyệt Yêu cầu mua hàng (PR)'), ('can_override_pr', 'Override Yêu cầu mua hàng (PR)'), ('can_create_po', 'Tạo Đơn mua hàng (PO)'), ('can_read_po', 'Xem Đơn mua hàng (PO)'), ('can_update_po', 'Sửa Đơn mua hàng (PO)'), ('can_delete_po', 'Xoá Đơn mua hàng (PO)'), ('can_approve_po', 'Duyệt Đơn mua hàng (PO)'), ('can_override_po', 'Override Đơn mua hàng (PO)'), ('can_create_reports', 'Tạo Báo cáo'), ('can_read_reports', 'Xem Báo cáo'), ('can_update_reports', 'Sửa Báo cáo'), ('can_delete_reports', 'Xoá Báo cáo'), ('can_approve_reports', 'Duyệt Báo cáo'), ('can_override_reports', 'Override Báo cáo')]},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=30, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, null=True, verbose_name='Thay đổi'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Lý do'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Loại đối tượng'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xoá'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete (FR-USER-01): đánh dấu đã xoá nhưng giữ lại để audit.', verbose_name='Đã xoá'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Quản lý kho'), ('STAFF', 'Nhân viên kho'), ('QC', 'Nhân viên QC'), ('PURCHASING', 'Nhân viên mua hàng'), ('ACCOUNTANT', 'Kế toán'), ('ADMIN', 'Quản trị viên')], help_text='Vai trò RBAC — quyết định permission matrix.', max_length=20, verbose_name='Vai trò'),
        ),
    ]
