# Generated by Django 5.2 on 2026-07-25 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_auditlog_options_alter_user_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('WAREHOUSE', 'Kho'), ('QC', 'QC'), ('PURCHASING', 'Mua hàng'), ('ACCOUNTING', 'Kế toán')], help_text='Phòng ban để xác định người nộp/người duyệt trong luồng phê duyệt. Bỏ trống cho Admin (không thuộc phòng ban cụ thể).', max_length=20, verbose_name='Phòng ban'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='True nếu user là quản lý của "department" — được duyệt/hủy phiếu của nhân viên cùng phòng ban.', verbose_name='Là quản lý phòng ban'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, verbose_name='Nội dung thông báo')),
                ('target_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mã đối tượng')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Loại đối tượng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='accounts_no_recipie_646219_idx')],
            },
        ),
    ]
