# Generated by Django 5.2 on 2026-07-25 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_populate_department_is_manager'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(max_length=64, verbose_name='Mã đối tượng')),
                ('department', models.CharField(choices=[('WAREHOUSE', 'Kho'), ('QC', 'QC'), ('PURCHASING', 'Mua hàng'), ('ACCOUNTING', 'Kế toán')], help_text='Chỉ quản lý (is_manager=True) của phòng ban này được quyết định.', max_length=20, verbose_name='Phòng ban duyệt')),
                ('action_label', models.CharField(max_length=255, verbose_name='Nội dung yêu cầu duyệt')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nộp')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('decision_note', models.TextField(blank=True, verbose_name='Ghi chú quyết định')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_decided', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Người nộp')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Loại đối tượng')),
            ],
            options={
                'verbose_name': 'Yêu cầu duyệt',
                'verbose_name_plural': 'Yêu cầu duyệt',
                'ordering': ['-submitted_at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='accounts_ap_target__8970c2_idx'), models.Index(fields=['department', 'status'], name='accounts_ap_departm_b18883_idx')],
            },
        ),
    ]
