# Generated by Django 5.2 on 2026-07-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_menu_access_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('target_type', 'target_id'), name='unique_pending_approval_per_target'),
        ),
    ]
