# Generated by Django 5.2 on 2026-07-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_approval_unique_pending_approval_per_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xoá'), ('APPROVE', 'Duyệt'), ('REJECT', 'Từ chối'), ('CANCEL', 'Hủy'), ('OVERRIDE', 'Override'), ('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('LOGIN_FAILED', 'Đăng nhập thất bại')], max_length=30, verbose_name='Hành động'),
        ),
    ]
