# Generated by Django 5.2.16 on 2026-08-03 22:12

from django.db import migrations


def create_permissions_now(apps, schema_editor):
    """Django chỉ thật sự tạo ``Permission`` row cho ``Meta.permissions`` mới
    qua signal ``post_migrate``, phát 1 lần duy nhất ở CUỐI toàn bộ lệnh
    ``migrate`` (sau khi mọi migration, kể cả ``RunPython`` trong chính
    migration này, đã chạy xong) — nên ``grant_exchange_rate_menu_to_existing_admins``
    bên dưới không thể ``Permission.objects.get(codename='can_view_menu_exchange_rate')``
    ngay được nếu không tự tạo permission đó trước. Gọi thẳng
    ``create_permissions()`` ở đây, set tạm ``models_module`` về giá trị
    truthy bất kỳ, rồi khôi phục lại trạng thái GỐC ngay sau đó trong
    ``finally``.

    ``apps`` trong 1 migration thật là ``StateApps`` (registry lịch sử) —
    ``apps.get_app_config('accounts')`` trả về ``AppConfigStub``
    (``django.db.migrations.state.AppConfigStub``), và stub này KHÔNG hề định
    nghĩa thuộc tính ``models_module`` (khác ``AppConfig`` thật luôn có, dù có
    thể là ``None``) — đọc thẳng ``app_config.models_module`` ở đây sẽ raise
    ``AttributeError``, không phải trả về ``None``. Dùng ``getattr``/``hasattr``
    để phân biệt "thuộc tính chưa từng tồn tại" (stub — xoá lại bằng ``del``
    trong ``finally``) với "tồn tại nhưng giá trị falsy" (tránh gán cứng
    ``None``/xoá mất trạng thái registry thật khi hàm này được gọi lại trực
    tiếp từ test với ``apps`` = registry thật, có ``models_module`` đã set).
    """
    from django.contrib.auth.management import create_permissions
    app_config = apps.get_app_config('accounts')
    had_attr = hasattr(app_config, 'models_module')
    original_models_module = getattr(app_config, 'models_module', None)
    try:
        app_config.models_module = original_models_module or True
        create_permissions(app_config, apps=apps, using=schema_editor.connection.alias, verbosity=0)
    finally:
        if had_attr:
            app_config.models_module = original_models_module
        else:
            del app_config.models_module


def grant_exchange_rate_menu_to_existing_admins(apps, schema_editor):
    """``sync_roles()``/``sync_user_permissions()`` (accounts/rbac.py) không tự
    cấp lại quyền hiệu lực cho user ĐÃ TỒN TẠI — quyền hiệu lực chỉ đến từ
    ``user.user_permissions`` trực tiếp, được ghi khi user được TẠO MỚI hoặc
    RENAME role, không phải mỗi lần ``sync_roles()`` chạy (xem
    ``accounts/backends.py::DirectPermissionsBackend``). Backfill thủ công ở
    đây cho Admin hiện có, dùng ``.add()`` — KHÔNG ``.set()`` — để giữ nguyên
    phân quyền chi tiết khác của từng user.
    """
    User = apps.get_model('accounts', 'User')
    Permission = apps.get_model('auth', 'Permission')
    db_alias = schema_editor.connection.alias
    perm = Permission.objects.using(db_alias).get(
        content_type__app_label='accounts', codename='can_view_menu_exchange_rate')
    for user in User.objects.using(db_alias).filter(role='ADMIN'):
        user.user_permissions.add(perm)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_reseed_pr_create_update_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_grn', 'Tạo GRN (phiếu nhập)'), ('can_read_grn', 'Xem GRN (phiếu nhập)'), ('can_update_grn', 'Sửa GRN (phiếu nhập)'), ('can_delete_grn', 'Xoá GRN (phiếu nhập)'), ('can_approve_grn', 'Duyệt GRN (phiếu nhập)'), ('can_override_grn', 'Override GRN (phiếu nhập)'), ('can_create_gin', 'Tạo GIN (phiếu xuất)'), ('can_read_gin', 'Xem GIN (phiếu xuất)'), ('can_update_gin', 'Sửa GIN (phiếu xuất)'), ('can_delete_gin', 'Xoá GIN (phiếu xuất)'), ('can_approve_gin', 'Duyệt GIN (phiếu xuất)'), ('can_override_gin', 'Override GIN (phiếu xuất)'), ('can_create_opname', 'Tạo Kiểm kê kho (Stock Opname)'), ('can_read_opname', 'Xem Kiểm kê kho (Stock Opname)'), ('can_update_opname', 'Sửa Kiểm kê kho (Stock Opname)'), ('can_delete_opname', 'Xoá Kiểm kê kho (Stock Opname)'), ('can_approve_opname', 'Duyệt Kiểm kê kho (Stock Opname)'), ('can_override_opname', 'Override Kiểm kê kho (Stock Opname)'), ('can_create_qc', 'Tạo Kiểm tra chất lượng (QC)'), ('can_read_qc', 'Xem Kiểm tra chất lượng (QC)'), ('can_update_qc', 'Sửa Kiểm tra chất lượng (QC)'), ('can_delete_qc', 'Xoá Kiểm tra chất lượng (QC)'), ('can_approve_qc', 'Duyệt Kiểm tra chất lượng (QC)'), ('can_override_qc', 'Override Kiểm tra chất lượng (QC)'), ('can_create_pr', 'Tạo Yêu cầu mua hàng (PR)'), ('can_read_pr', 'Xem Yêu cầu mua hàng (PR)'), ('can_update_pr', 'Sửa Yêu cầu mua hàng (PR)'), ('can_delete_pr', 'Xoá Yêu cầu mua hàng (PR)'), ('can_approve_pr', 'Duyệt Yêu cầu mua hàng (PR)'), ('can_override_pr', 'Override Yêu cầu mua hàng (PR)'), ('can_create_po', 'Tạo Đơn mua hàng (PO)'), ('can_read_po', 'Xem Đơn mua hàng (PO)'), ('can_update_po', 'Sửa Đơn mua hàng (PO)'), ('can_delete_po', 'Xoá Đơn mua hàng (PO)'), ('can_approve_po', 'Duyệt Đơn mua hàng (PO)'), ('can_override_po', 'Override Đơn mua hàng (PO)'), ('can_create_reports', 'Tạo Báo cáo'), ('can_read_reports', 'Xem Báo cáo'), ('can_update_reports', 'Sửa Báo cáo'), ('can_delete_reports', 'Xoá Báo cáo'), ('can_approve_reports', 'Duyệt Báo cáo'), ('can_override_reports', 'Override Báo cáo'), ('can_view_menu_warehouse', 'Truy cập menu Kho hàng'), ('can_view_menu_catalog', 'Truy cập menu Sản phẩm (Danh mục)'), ('can_view_menu_partners', 'Truy cập menu Nhà cung cấp'), ('can_view_menu_inventory', 'Truy cập menu Tồn kho'), ('can_view_menu_handoff', 'Truy cập menu Phiếu chờ nhận hàng'), ('can_view_menu_user_mgmt', 'Truy cập menu Quản lý user'), ('can_view_menu_audit_log', 'Truy cập menu Nhật ký hành động'), ('can_view_menu_exchange_rate', 'Truy cập menu Tỷ giá ngoại tệ')]},
        ),
        migrations.RunPython(create_permissions_now, noop_reverse),
        migrations.RunPython(grant_exchange_rate_menu_to_existing_admins, noop_reverse),
    ]
