# Generated by Django 5.2.16 on 2026-07-24 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(help_text='Mã lô, vd LOT-0001.', max_length=40, unique=True)),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Ngày sản xuất')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng')),
                ('qty_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('PARTIAL_USED', 'Đã dùng một phần'), ('QUARANTINE', 'Chờ xử lý (QC fail/partial)'), ('EXPIRED', 'Hết hạn'), ('CLOSED', 'Đã đóng (dùng hết)')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='partners.supplier')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['exp_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.PositiveIntegerField(default=0, help_text='BR-WM-001: không cho âm.')),
                ('qty_reserved', models.PositiveIntegerField(default=0)),
                ('qty_quarantine', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'ordering': ['warehouse__code', 'product__product_code'],
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_inventory_product_warehouse')],
            },
        ),
    ]
