# Generated by Django 5.2 on 2026-07-24 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Nhập kho'), ('ISSUE', 'Xuất kho'), ('ADJUSTMENT', 'Điều chỉnh'), ('TRANSFER_OUT', 'Điều chuyển (xuất)'), ('TRANSFER_IN', 'Điều chuyển (nhập)')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(editable=False, help_text='Tự sinh: TRF-YYYYMM-XXX.', max_length=30, unique=True)),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='inventory.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='warehouse.location')),
                ('new_batch', models.ForeignKey(blank=True, help_text='Batch mới tách ra tại vị trí đích.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_from', to='inventory.batch')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_in', to='warehouse.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
