# Generated by Django 5.2 on 2026-07-25 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_movement_type_stocktransfer'),
        ('receiving', '0002_grnitem_qty_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='grn_item',
            field=models.ForeignKey(blank=True, help_text='Nguồn gốc GRN item (lineage) — null cho batch không sinh trực tiếp từ GRN. Batch con tách ra qua move_batch_qty copy lại field này từ batch nguồn.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='receiving.grnitem'),
        ),
    ]
