# Generated by Django 5.2 on 2026-07-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batch_grn_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='qty_quarantine',
        ),
    ]
