# Generated by Django 5.2.16 on 2026-07-25 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_alter_product_category_and_more'),
        ('inventory', '0005_remove_inventory_qty_quarantine'),
        ('partners', '0004_alter_supplier_options_alter_supplier_contact_email_and_more'),
        ('receiving', '0003_alter_grn_options_alter_grnitem_options_and_more'),
        ('warehouse', '0003_alter_location_options_alter_warehouse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['exp_date', 'created_at'], 'verbose_name': 'Lô hàng', 'verbose_name_plural': 'Lô hàng'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['warehouse__code', 'product__product_code'], 'verbose_name': 'Tồn kho', 'verbose_name_plural': 'Tồn kho'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lịch sử tồn kho', 'verbose_name_plural': 'Lịch sử tồn kho'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiếu điều chuyển', 'verbose_name_plural': 'Phiếu điều chuyển'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(help_text='Mã lô, vd LOT-0001.', max_length=40, unique=True, verbose_name='Mã lô'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='grn_item',
            field=models.ForeignKey(blank=True, help_text='Nguồn gốc GRN item (lineage) — null cho batch không sinh trực tiếp từ GRN. Batch con tách ra qua move_batch_qty copy lại field này từ batch nguồn.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='receiving.grnitem', verbose_name='Dòng GRN nguồn'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='warehouse.location', verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_received',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng nhận'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng đã dùng'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('PARTIAL_USED', 'Đã dùng một phần'), ('QUARANTINE', 'Chờ xử lý (QC fail/partial)'), ('EXPIRED', 'Hết hạn'), ('CLOSED', 'Đã đóng (dùng hết)')], default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='partners.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qty_on_hand',
            field=models.PositiveIntegerField(default=0, help_text='BR-WM-001: không cho âm.', verbose_name='Tồn kho thực tế'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qty_reserved',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng đã giữ chỗ'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='warehouse.warehouse', verbose_name='Kho'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.batch', verbose_name='Lô hàng'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Nhập kho'), ('ISSUE', 'Xuất kho'), ('ADJUSTMENT', 'Điều chỉnh'), ('TRANSFER_OUT', 'Điều chuyển (xuất)'), ('TRANSFER_IN', 'Điều chuyển (nhập)')], max_length=20, verbose_name='Loại giao dịch'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='qty',
            field=models.IntegerField(help_text='Dương = nhập, âm = xuất.', verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='qty_on_hand_after',
            field=models.PositiveIntegerField(verbose_name='Tồn sau giao dịch'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, help_text='Vd GRN-2607-0001, GIN-2607-0001.', max_length=50, verbose_name='Chứng từ tham chiếu'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='warehouse.warehouse', verbose_name='Kho'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='inventory.batch', verbose_name='Lô hàng'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='warehouse.location', verbose_name='Vị trí nguồn'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='new_batch',
            field=models.ForeignKey(blank=True, help_text='Batch mới tách ra tại vị trí đích.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_from', to='inventory.batch', verbose_name='Lô mới tại vị trí đích'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='qty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_in', to='warehouse.location', verbose_name='Vị trí đích'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_no',
            field=models.CharField(editable=False, help_text='Tự sinh: TRF-YYYYMM-XXX.', max_length=30, unique=True, verbose_name='Số phiếu điều chuyển'),
        ),
    ]
