# Generated by Django 5.2 on 2026-07-25 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_batch_options_alter_inventory_options_and_more'),
        ('quality', '0005_alter_qcinspection_options_and_more'),
        ('warehouse', '0004_warehouse_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('PENDING_RECEIPT', 'Chờ kho xác nhận'), ('ACTIVE', 'Đang hoạt động'), ('PARTIAL_USED', 'Đã dùng một phần'), ('QUARANTINE', 'Chờ xử lý (QC fail/partial)'), ('EXPIRED', 'Hết hạn'), ('CLOSED', 'Đã đóng (dùng hết)')], default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='WarehouseHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('ACCEPTED', 'Đã nhận'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('reject_reason', models.CharField(blank=True, max_length=255, verbose_name='Lý do từ chối')),
                ('reject_destination', models.CharField(blank=True, choices=[('BACK_TO_QC', 'Trả về QC'), ('TO_SCRAP', 'Chuyển kho phế')], max_length=20, verbose_name='Xử lý khi từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Bỏ trống thì báo toàn bộ nhân viên phụ trách kho đích.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_handoffs', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận chỉ định')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='handoff', to='inventory.batch', verbose_name='Lô hàng')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_handoffs_decided', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs', to='warehouse.warehouse', verbose_name='Kho đích')),
                ('qc_inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs', to='quality.qcinspection', verbose_name='Đợt kiểm QC')),
            ],
            options={
                'verbose_name': 'Phiếu chờ nhận hàng',
                'verbose_name_plural': 'Phiếu chờ nhận hàng',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'assigned_to'], name='inventory_w_status_5d53e3_idx')],
            },
        ),
    ]
