# Generated by Django 5.2 on 2026-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_preferred_supplier'),
        ('inventory', '0007_alter_batch_status_warehousehandoff'),
        ('partners', '0005_supplier_managed_by'),
        ('receiving', '0004_alter_grn_status'),
        ('warehouse', '0004_warehouse_staff'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('qty_used__lte', models.F('qty_received'))), name='batch_qty_used_lte_received'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('qty_reserved__lte', models.F('qty_on_hand'))), name='inventory_reserved_lte_on_hand'),
        ),
    ]
