# Generated by Django 5.2.16 on 2026-07-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_batch_batch_qty_used_lte_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousehandoff',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('ACCEPTED', 'Đã nhận'), ('REJECTED', 'Đã từ chối'), ('CANCELLED', 'Đã huỷ (kiểm kê)')], default='PENDING', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
