"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Đọc biến môi trường từ file .env ở thư mục gốc dự án (mật khẩu DB, SECRET_KEY, ...)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()]

# Chưa có reverse proxy nào đứng trước app (chưa Docker/deploy — xem CLAUDE.md), nên
# header X-Forwarded-For do chính client tự set, không phải proxy — KHÔNG được tin
# dùng để xác định IP thật (vd. key rate-limit login theo IP, xem accounts.audit.client_ip).
# Chỉ bật True khi thật sự có 1 reverse proxy tin cậy đứng trước và proxy đó tự ghi đè
# header này (không cho client tự set qua nó).
TRUST_X_FORWARDED_FOR = os.getenv('TRUST_X_FORWARDED_FOR', 'False').lower() in ('true', '1', 'yes')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- NVL/WMS apps (Phase 1) ---
    'accounts',     # User & Permission (RBAC, audit trail)
    'warehouse',    # Quản lý kho
    'catalog',      # Master data: sản phẩm / SKU
    'partners',     # Master data: nhà cung cấp
    'purchasing',   # PO (stub ở Phase 1, đầy đủ ở Phase 5)
    'inventory',    # Tồn kho / Batch (schema ở Phase 1)

    # --- NVL/WMS apps (Phase 2) ---
    'receiving',    # GRN (Phiếu Nhập)
    'quality',      # Quality Control (QC)

    # --- NVL/WMS apps (Phase 3) ---
    'shipping',     # GIN (Phiếu Xuất)

    # --- NVL/WMS apps (Phase 4) ---
    'stocktake',    # Kiểm kê (Stock Opname)

    # --- NVL/WMS apps (Phase 6) ---
    'reports',      # Reporting & Analytics
]

# Custom user model (NVL/WMS): thêm role RBAC + soft delete.
# BẮT BUỘC khai báo trước lần migrate đầu tiên — đổi về sau rất khó.
AUTH_USER_MODEL = 'accounts.User'

# Quyền hiệu lực chỉ tính từ user_permissions trực tiếp, không cộng dồn từ Group
# (xem accounts/backends.py) — để "phân quyền chi tiết cho từng user" (FR-USER-04
# mở rộng) có thể THU HỒI, không chỉ thêm, so với mặc định vai trò.
AUTHENTICATION_BACKENDS = ['accounts.backends.DirectPermissionsBackend']

# Điều hướng đăng nhập/đăng xuất (FR-USER-03).
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Email (FR-USER-01: gửi mật khẩu tạm khi tạo user).
# Dev mặc định in ra console (xem terminal runserver); production cấu hình SMTP
# qua .env sau. Khi chạy test, Django tự override sang backend locmem (mail.outbox).
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@nvl-wms.local')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.notifications',
                'accounts.context_processors.sidebar_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'ql-nvl'),
        'USER': os.getenv('DB_USER', 'qlnvl'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Nguồn asset commit vào repo (vendor offline) — khác với /static/ (output của
# collectstatic, đã gitignore) để tránh assets vendor bị bỏ qua khi commit.
STATICFILES_DIRS = [BASE_DIR / 'assets']

# Ảnh evidence QC (FR-QC-06) + ảnh reference tiêu chuẩn QC — file do user upload,
# không commit vào repo (xem .gitignore: /media/).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
