# Generated by Django 5.2.16 on 2026-07-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QcInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_no', models.CharField(editable=False, help_text='Tự sinh: QC-YYYYMM-XXX.', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING_QC', 'Chờ QC'), ('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('PARTIAL_PASS', 'Đạt một phần')], default='PENDING_QC', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QcInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=100)),
                ('expected_value', models.CharField(blank=True, max_length=100)),
                ('actual_value', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt')], max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QcCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Vd: Bột mì, Đường...', max_length=100)),
                ('name', models.CharField(help_text='Vd: Ngoại hình, Trọng lượng, Seal integrity.', max_length=100)),
                ('pass_rule', models.CharField(blank=True, max_length=255)),
                ('fail_rule', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'QC criteria',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_qc_criteria_category_name')],
            },
        ),
    ]
