# Generated by Django 5.2.16 on 2026-07-24 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinspection',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='receiving.grn'),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qcinspectionitem',
            name='grn_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_items', to='receiving.grnitem'),
        ),
        migrations.AddField(
            model_name='qcinspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.qcinspection'),
        ),
    ]
