# Generated by Django 5.2.16 on 2026-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qccriteria',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Ảnh mẫu minh hoạ tiêu chuẩn (vd: màu sắc đạt, seal integrity đạt).', null=True, upload_to='qc_criteria_ref/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='qcinspectionitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh evidence thực tế lúc kiểm (FR-QC-06).', null=True, upload_to='qc_evidence/%Y/%m/'),
        ),
    ]
