# Generated by Django 5.2 on 2026-07-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_qccriteria_reference_image_qcinspectionitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinspection',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='override_note',
            field=models.TextField(blank=True),
        ),
    ]
