# Generated by Django 5.2.16 on 2026-07-25 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_qcinspection_overridden_at_and_more'),
        ('receiving', '0003_alter_grn_options_alter_grnitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qcinspection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiếu kiểm tra QC', 'verbose_name_plural': 'Phiếu kiểm tra QC'},
        ),
        migrations.AlterModelOptions(
            name='qcinspectionitem',
            options={'verbose_name': 'Dòng kiểm tra QC', 'verbose_name_plural': 'Dòng kiểm tra QC'},
        ),
        migrations.AlterField(
            model_name='qccriteria',
            name='category',
            field=models.CharField(help_text='Vd: Bột mì, Đường...', max_length=100, verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='qccriteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='qccriteria',
            name='fail_rule',
            field=models.CharField(blank=True, max_length=255, verbose_name='Điều kiện không đạt'),
        ),
        migrations.AlterField(
            model_name='qccriteria',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='qccriteria',
            name='name',
            field=models.CharField(help_text='Vd: Ngoại hình, Trọng lượng, Seal integrity.', max_length=100, verbose_name='Tên tiêu chuẩn'),
        ),
        migrations.AlterField(
            model_name='qccriteria',
            name='pass_rule',
            field=models.CharField(blank=True, max_length=255, verbose_name='Điều kiện đạt'),
        ),
        migrations.AlterField(
            model_name='qccriteria',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Ảnh mẫu minh hoạ tiêu chuẩn (vd: màu sắc đạt, seal integrity đạt).', null=True, upload_to='qc_criteria_ref/%Y/%m/', verbose_name='Ảnh tham chiếu'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoàn tất lúc'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='receiving.grn', verbose_name='Phiếu GRN'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm tra'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm override'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Người override'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='override_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú override'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='qc_no',
            field=models.CharField(editable=False, help_text='Tự sinh: QC-YYYYMM-XXX.', max_length=30, unique=True, verbose_name='Số phiếu QC'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu lúc'),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='status',
            field=models.CharField(choices=[('PENDING_QC', 'Chờ QC'), ('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('PARTIAL_PASS', 'Đạt một phần')], default='PENDING_QC', max_length=20, verbose_name='Kết quả'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='actual_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giá trị thực tế'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='criteria_name',
            field=models.CharField(max_length=100, verbose_name='Tiêu chuẩn'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='expected_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giá trị chuẩn'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='grn_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_items', to='receiving.grnitem', verbose_name='Dòng GRN'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh evidence thực tế lúc kiểm (FR-QC-06).', null=True, upload_to='qc_evidence/%Y/%m/', verbose_name='Ảnh evidence'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.qcinspection', verbose_name='Phiếu QC'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='result',
            field=models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt')], max_length=10, verbose_name='Kết quả'),
        ),
    ]
