# Generated by Django 5.2 on 2026-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_alter_qcinspection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcinspection',
            name='status',
            field=models.CharField(choices=[('PENDING_QC', 'Chờ QC'), ('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('PARTIAL_PASS', 'Đạt một phần'), ('CANCELLED', 'Đã hủy')], default='PENDING_QC', max_length=20, verbose_name='Kết quả'),
        ),
    ]
