# Generated by Django 5.2 on 2026-07-27 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_alter_qcinspection_status'),
        ('receiving', '0004_alter_grn_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qcinspection',
            index=models.Index(fields=['status', 'started_at'], name='quality_qci_status_bdb30c_idx'),
        ),
    ]
