# Generated by Django 5.2 on 2026-07-27 15:27

import quality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_qcinspection_quality_qci_status_bdb30c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qccriteria',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Ảnh mẫu minh hoạ tiêu chuẩn (vd: màu sắc đạt, seal integrity đạt). Tối đa 5MB, JPG/PNG/WEBP.', null=True, upload_to='qc_criteria_ref/%Y/%m/', validators=[quality.models.validate_image_upload], verbose_name='Ảnh tham chiếu'),
        ),
        migrations.AlterField(
            model_name='qcinspectionitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh evidence thực tế lúc kiểm (FR-QC-06). Tối đa 5MB, JPG/PNG/WEBP.', null=True, upload_to='qc_evidence/%Y/%m/', validators=[quality.models.validate_image_upload], verbose_name='Ảnh evidence'),
        ),
    ]
