# Generated by Django 5.2 on 2026-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Ngày giao hàng dự kiến — dùng để theo dõi On time/Delayed (FR-PO-06).', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateField(blank=True, help_text='Ngày PO chuyển sang RECEIVED (set tự động 1 lần, dùng tính lead-time thực tế FR-PO-05).', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('APPROVED', 'Đã duyệt'), ('SENT', 'Đã gửi NCC'), ('PARTIAL_RECEIVED', 'Nhận một phần'), ('RECEIVED', 'Đã nhận đủ'), ('CLOSED', 'Đã đóng')], default='DRAFT', max_length=20),
        ),
    ]
