# Generated by Django 5.2 on 2026-07-25 12:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_qc_sampling_method_product_qc_sampling_value'),
        ('purchasing', '0002_purchaseorder_expected_delivery_date_and_more'),
        ('warehouse', '0002_warehouse_warehouse_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(editable=False, help_text='Tự sinh: PR-YYYYMM-XXX.', max_length=30, unique=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='purchasing.purchaseorder')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Kho đang thiếu hàng (chỉ kho loại MAIN).', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pr_items', to='catalog.product')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaserequest')),
            ],
        ),
    ]
