# Generated by Django 5.2.16 on 2026-07-25 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_alter_product_category_and_more'),
        ('partners', '0004_alter_supplier_options_alter_supplier_contact_email_and_more'),
        ('purchasing', '0003_purchaserequest_purchaserequestitem'),
        ('warehouse', '0003_alter_location_options_alter_warehouse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn mua hàng', 'verbose_name_plural': 'Đơn mua hàng'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'verbose_name': 'Dòng đơn mua hàng', 'verbose_name_plural': 'Dòng đơn mua hàng'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu mua hàng', 'verbose_name_plural': 'Yêu cầu mua hàng'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestitem',
            options={'verbose_name': 'Dòng yêu cầu mua hàng', 'verbose_name_plural': 'Dòng yêu cầu mua hàng'},
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Ngày giao hàng dự kiến — dùng để theo dõi On time/Delayed (FR-PO-06).', null=True, verbose_name='Ngày giao hàng dự kiến'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_no',
            field=models.CharField(help_text='Mã PO, vd PO-0001.', max_length=30, unique=True, verbose_name='Mã PO'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateField(blank=True, help_text='Ngày PO chuyển sang RECEIVED (set tự động 1 lần, dùng tính lead-time thực tế FR-PO-05).', null=True, verbose_name='Ngày nhận đủ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('APPROVED', 'Đã duyệt'), ('SENT', 'Đã gửi NCC'), ('PARTIAL_RECEIVED', 'Nhận một phần'), ('RECEIVED', 'Đã nhận đủ'), ('CLOSED', 'Đã đóng')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='partners.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseorder', verbose_name='Đơn mua hàng'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='qty_ordered',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng đặt'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='linked_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='purchasing.purchaseorder', verbose_name='PO liên kết'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lý do từ chối'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_no',
            field=models.CharField(editable=False, help_text='Tự sinh: PR-YYYYMM-XXX.', max_length=30, unique=True, verbose_name='Số yêu cầu'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='warehouse',
            field=models.ForeignKey(help_text='Kho đang thiếu hàng (chỉ kho loại MAIN).', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='warehouse.warehouse', verbose_name='Kho'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pr_items', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaserequest', verbose_name='Yêu cầu mua hàng'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='qty_requested',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng yêu cầu'),
        ),
    ]
