# Generated by Django 5.2 on 2026-07-26 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_alter_purchaseorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Chọn 1 nhân viên phòng Mua hàng cụ thể để xử lý yêu cầu này — để trống thì thông báo cho cả phòng Mua hàng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên mua hàng phụ trách'),
        ),
    ]
