# Generated by Django 5.2 on 2026-07-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchaserequest_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_no',
            field=models.CharField(editable=False, help_text='Tự sinh: PO-XXXX (tăng dần toàn hệ thống, không nhập tay — tránh trùng mã).', max_length=30, unique=True, verbose_name='Mã PO'),
        ),
    ]
