# Generated by Django 5.2 on 2026-07-26 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_alter_purchaseorder_po_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Set tự động = người bấm Tạo PO — dùng để giới hạn nhân viên phòng Mua hàng thường chỉ xem PO do chính mình tạo (xem purchasing.views._po_can_view_all).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
    ]
