# Generated by Django 5.2 on 2026-07-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0010_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Tự tạo'), ('FROM_PR', 'Từ yêu cầu mua hàng')], default='MANUAL', help_text='Tự tạo trực tiếp hay chuyển đổi từ 1 Yêu cầu mua hàng đã duyệt (set tự động, không sửa tay).', max_length=20, verbose_name='Nguồn tạo'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Tự đề xuất'), ('MIN_LEVEL', 'Gợi ý dưới Min Level')], default='MANUAL', help_text='Tự đề xuất hay tạo từ gợi ý tồn kho dưới Min Level (set tự động, không sửa tay).', max_length=20, verbose_name='Nguồn tạo'),
        ),
    ]
