# Generated by Django 5.2 on 2026-07-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_purchaseorder_source_purchaserequest_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='close_reason',
            field=models.TextField(blank=True, help_text='Bắt buộc khi đóng PO từ SENT/PARTIAL_RECEIVED (NCC chưa giao đủ hàng); không bắt buộc khi đóng từ RECEIVED (đã nhận đủ, chỉ archive).', verbose_name='Lý do đóng sớm'),
        ),
    ]
