# Generated by Django 5.2 on 2026-07-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_purchaseorder_close_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING_DEPT', 'Chờ duyệt bộ phận'), ('PENDING_PUR', 'Chờ duyệt Mua hàng'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
