# Generated by Django 5.2.16 on 2026-08-02 15:27

"""PUR-FND-06: chặn cùng 1 Product xuất hiện 2 dòng trong 1 PO — xem
``purchasing.services.find_duplicate_po_products()`` (báo cáo tầng ứng dụng,
chạy TRƯỚC migration này để biết trước quy mô dữ liệu cần dọn) và mục 9 của
``docs/pur/01_foundation_fsd.md``.

Guard dưới đây viết ĐỘC LẬP với ``purchasing.models``/``purchasing.services``
hiện tại (dùng historical model qua ``apps.get_model()``) để migration này vẫn
chạy đúng kể cả nhiều năm sau khi model/service thật đã đổi form/tên field/bị
xoá hẳn — không import lại ``find_duplicate_po_products()``. Guard luôn có mặt
ngay trước ``AddConstraint``, không có nhánh bỏ qua dù tiền kiểm ở Bước 1 báo 0
vi phạm (thời gian giữa tiền kiểm và lúc thật sự chạy migrate trên production
vẫn có thể phát sinh PO vi phạm mới).
"""
from django.db import migrations, models
from django.db.models import Count


def ensure_no_duplicate_po_products(apps, schema_editor):
    PurchaseOrderItem = apps.get_model('purchasing', 'PurchaseOrderItem')

    duplicates = (
        PurchaseOrderItem.objects
        .values('purchase_order_id', 'product_id')
        .annotate(item_count=Count('id'))
        .filter(item_count__gt=1)
    )

    if duplicates.exists():
        raise RuntimeError(
            'Không thể thêm UniqueConstraint(purchase_order, product) — còn PO vi phạm: '
            f'{list(duplicates)}. Xử lý thủ công (gộp/xoá dòng thừa theo nghiệp vụ thật của '
            'từng PO) rồi chạy lại migration này.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_preferred_supplier'),
        ('purchasing', '0014_backfill_pr_two_stage_status'),
    ]

    operations = [
        migrations.RunPython(ensure_no_duplicate_po_products, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='unique_po_product'),
        ),
    ]
