# Generated by Django 5.2.16 on 2026-08-02 15:36

"""PUR-FND-02: thêm ``sent_at``/``email_status`` vào ``PurchaseOrder``.

``sent_at`` không backfill suy đoán — luôn để ``null`` cho PO đã tồn tại
(không suy ra ``sent_at = created_at``, đó chính là sai số PUR-FND-03 đang sửa).

Data migration cho ``email_status`` phân biệt đúng 2 nhóm PO cũ theo
``status`` (không dùng ``sent_at IS NULL`` để suy luận — cả 2 nhóm đều
``null`` sau bước AddField, không phân biệt được nếu chỉ nhìn ``sent_at``):
PO đã từng ``SENT`` trở lên (``{SENT, PARTIAL_RECEIVED, RECEIVED, CLOSED}``)
→ ``UNKNOWN_LEGACY`` (code cũ luôn trả ``True`` bất kể kết quả thật, không thể
suy ra SENT/FAILED); PO còn ``{DRAFT, APPROVED}`` → giữ nguyên default
``NOT_ATTEMPTED`` (thật sự chưa gửi, không cần backfill riêng). Xem mục 9
``docs/pur/01_foundation_fsd.md``.
"""
from django.db import migrations, models


def backfill_legacy_email_status(apps, schema_editor):
    PurchaseOrder = apps.get_model('purchasing', 'PurchaseOrder')
    PurchaseOrder.objects.filter(
        status__in=['SENT', 'PARTIAL_RECEIVED', 'RECEIVED', 'CLOSED'],
    ).update(email_status='UNKNOWN_LEGACY')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_purchaseorderitem_unique_po_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='email_status',
            field=models.CharField(choices=[('NOT_ATTEMPTED', 'Chưa gửi'), ('SKIPPED_NO_EMAIL', 'NCC chưa có email'), ('SENT', 'Đã gửi'), ('FAILED', 'Gửi thất bại'), ('UNKNOWN_LEGACY', 'Không rõ (dữ liệu trước nâng cấp)')], default='NOT_ATTEMPTED', help_text='Kết quả lần gửi email PO gần nhất cho NCC (send_po()/retry_po_email()).', max_length=20, verbose_name='Trạng thái gửi email'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Set 1 lần trong send_po() khi APPROVED -> SENT, bất kể email gửi được hay không — là thời điểm hệ thống phát hành PO, không phải lúc NCC xác nhận đã nhận. PO tạo trước khi có field này để trống (không suy đoán bằng created_at).', null=True, verbose_name='Thời điểm gửi NCC'),
        ),
        migrations.RunPython(backfill_legacy_email_status, noop_reverse),
    ]
