# Generated by Django 5.2.16 on 2026-08-03 08:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_preferred_supplier'),
        ('purchasing', '0016_purchaseorder_email_status_purchaseorder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='cost_center',
            field=models.CharField(default='', help_text='Bắt buộc — khoá ngân sách theo quyết định #2 (cost_center + budget_category dòng PR).', max_length=50, verbose_name='Trung tâm chi phí'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='department_snapshot',
            field=models.CharField(blank=True, choices=[('WAREHOUSE', 'Kho'), ('QC', 'QC'), ('PURCHASING', 'Mua hàng'), ('ACCOUNTING', 'Kế toán')], default='', editable=False, help_text='Set tự động trong submit_purchase_request() — bất biến sau khi set, không đọc lại requested_by.department nếu người đó đổi phòng ban sau này.', max_length=20, verbose_name='Phòng ban (snapshot lúc nộp)'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='project',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dự án (tuỳ chọn)'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='budget_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhóm ngân sách/Tài khoản'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='currency',
            field=models.CharField(choices=[('VND', 'VND'), ('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CNY', 'CNY')], default='VND', max_length=3, verbose_name='Loại tiền'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='estimated_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá ước tính'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='non_catalog_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tên hàng (chưa có trong danh mục)'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='non_catalog_note',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả/quy cách (non-catalog)'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='non_catalog_uom',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Đơn vị tính (đề xuất)'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='qty_approved',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng được duyệt'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='qty_cancelled',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng đã huỷ (phần còn mở)'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cần hàng'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pr_items', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('VND', 'VND'), ('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CNY', 'CNY')], max_length=3, verbose_name='Loại tiền')),
                ('rate_date', models.DateField(verbose_name='Ngày áp dụng')),
                ('rate_to_vnd', models.DecimalField(decimal_places=6, help_text='1 đơn vị ngoại tệ = ? VND.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tỷ giá quy đổi VND')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Tỷ giá ngoại tệ',
                'verbose_name_plural': 'Tỷ giá ngoại tệ',
                'ordering': ['-rate_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'rate_date'), name='unique_currency_rate_date'), models.CheckConstraint(condition=models.Q(('currency', 'VND'), _negated=True), name='exchange_rate_currency_not_vnd')],
            },
        ),
        migrations.CreateModel(
            name='ProcurementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no_snapshot', models.CharField(blank=True, editable=False, max_length=30, verbose_name='Số PO (lưu vết)')),
                ('product_code_snapshot', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Mã sản phẩm (lưu vết)')),
                ('qty_allocated', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng phân bổ')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hiệu lực'), ('RELEASED', 'Đã giải phóng')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('released_reason', models.TextField(blank=True, verbose_name='Lý do giải phóng')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm giải phóng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo phân bổ')),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='purchasing.purchaseorderitem', verbose_name='Dòng đơn mua hàng')),
                ('pr_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='purchasing.purchaserequestitem', verbose_name='Dòng yêu cầu mua hàng')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người giải phóng')),
            ],
            options={
                'verbose_name': 'Phân bổ PR-PO',
                'verbose_name_plural': 'Phân bổ PR-PO',
                'constraints': [models.CheckConstraint(condition=models.Q(('status', 'RELEASED'), ('po_item__isnull', False), _connector='OR'), name='active_allocation_requires_po_item'), models.CheckConstraint(condition=models.Q(models.Q(('released_at__isnull', True), ('released_by__isnull', True), ('released_reason', ''), ('status', 'ACTIVE')), models.Q(('released_at__isnull', False), ('status', 'RELEASED'), models.Q(('released_reason', ''), _negated=True)), _connector='OR'), name='allocation_release_fields_match_status'), models.CheckConstraint(condition=models.Q(('qty_allocated__gte', 1)), name='allocation_qty_positive'), models.CheckConstraint(condition=models.Q(models.Q(('po_no_snapshot', ''), _negated=True), models.Q(('product_code_snapshot', ''), _negated=True)), name='allocation_snapshots_required')],
            },
        ),
    ]
