# Generated by Django 5.2.16 on 2026-07-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text='Mã SKU, vd NVL-0001.', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('uom', models.CharField(help_text='vd kg, cái, thùng.', max_length=20, verbose_name='Đơn vị tính')),
                ('min_level', models.PositiveIntegerField(blank=True, help_text='Ngưỡng tồn kho tối thiểu.', null=True)),
                ('max_level', models.PositiveIntegerField(blank=True, help_text='Ngưỡng tồn kho tối đa.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['product_code'],
            },
        ),
    ]
