# Generated by Django 5.2 on 2026-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='holding_cost_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% chi phí lưu kho/năm trên đơn giá bình quân (H) — dùng tính EOQ (FR-INV-05).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ordering_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chi phí đặt hàng mỗi lần (S, VNĐ) — dùng tính EOQ (FR-INV-05).', max_digits=14, null=True),
        ),
    ]
