# Generated by Django 5.2 on 2026-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_holding_cost_rate_product_ordering_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qc_sampling_method',
            field=models.CharField(choices=[('PERCENT', '% trên qty nhận'), ('FIXED', 'Số lượng cố định')], default='PERCENT', help_text='Cách tính cỡ mẫu QC gợi ý (mục 2b QC Criteria & Sampling).', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='qc_sampling_value',
            field=models.PositiveIntegerField(default=10, help_text='PERCENT: % trên qty_received (vd 10 = 10%). FIXED: số lượng cố định.'),
        ),
    ]
