# Generated by Django 5.2.16 on 2026-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_qc_sampling_method_product_qc_sampling_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_code'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='holding_cost_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% chi phí lưu kho/năm trên đơn giá bình quân (H) — dùng tính EOQ (FR-INV-05).', max_digits=5, null=True, verbose_name='Tỷ lệ chi phí lưu kho (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_level',
            field=models.PositiveIntegerField(blank=True, help_text='Ngưỡng tồn kho tối đa.', null=True, verbose_name='Ngưỡng tồn tối đa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_level',
            field=models.PositiveIntegerField(blank=True, help_text='Ngưỡng tồn kho tối thiểu.', null=True, verbose_name='Ngưỡng tồn tối thiểu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ordering_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chi phí đặt hàng mỗi lần (S, VNĐ) — dùng tính EOQ (FR-INV-05).', max_digits=14, null=True, verbose_name='Chi phí đặt hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(help_text='Mã SKU, vd NVL-0001.', max_length=30, unique=True, verbose_name='Mã SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qc_sampling_method',
            field=models.CharField(choices=[('PERCENT', '% trên qty nhận'), ('FIXED', 'Số lượng cố định')], default='PERCENT', help_text='Cách tính cỡ mẫu QC gợi ý (mục 2b QC Criteria & Sampling).', max_length=10, verbose_name='Cách lấy mẫu QC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qc_sampling_value',
            field=models.PositiveIntegerField(default=10, help_text='PERCENT: % trên qty_received (vd 10 = 10%). FIXED: số lượng cố định.', verbose_name='Giá trị lấy mẫu QC'),
        ),
    ]
