# Generated by Django 5.2 on 2026-07-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_holding_cost_rate'),
        ('partners', '0005_supplier_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, help_text='NCC ưu tiên cho SKU này — gợi ý tự động khi tạo PO từ yêu cầu mua hàng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_products', to='partners.supplier', verbose_name='Nhà cung cấp ưu tiên'),
        ),
    ]
