# Generated by Django 5.2.16 on 2026-07-24 09:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0002_stockmovement'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gin_no', models.CharField(editable=False, help_text='Tự sinh: GIN-YYYYMM-XXX.', max_length=30, unique=True)),
                ('reference_type', models.CharField(choices=[('PO', 'Đơn mua hàng'), ('PRODUCTION', 'Sản xuất'), ('SALES', 'Bán hàng')], max_length=20)),
                ('reference_no', models.CharField(blank=True, help_text='Vd PO-0001 (khi PO), hoặc mã lệnh SX/đơn bán ngoài hệ thống.', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PICKING', 'Đang soạn hàng'), ('ISSUED', 'Đã xuất'), ('CLOSED', 'Đã đóng')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gins_requested', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gins', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_issued', models.PositiveIntegerField(default=0, help_text='FR-GIN-05: qty thực xuất, có thể khác qty_requested.')),
                ('gin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.gin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gin_items', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='GinBatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_allocated', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_override', models.BooleanField(default=False, help_text='True nếu người dùng đổi batch khác gợi ý FIFO (FR-GIN-03).')),
                ('override_reason', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gin_allocations', to='inventory.batch')),
                ('gin_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='shipping.ginitem')),
            ],
        ),
    ]
