# Generated by Django 5.2.16 on 2026-07-25 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_alter_product_category_and_more'),
        ('inventory', '0006_alter_batch_options_alter_inventory_options_and_more'),
        ('shipping', '0001_initial'),
        ('warehouse', '0003_alter_location_options_alter_warehouse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiếu xuất kho', 'verbose_name_plural': 'Phiếu xuất kho'},
        ),
        migrations.AlterModelOptions(
            name='ginbatchallocation',
            options={'verbose_name': 'Phân bổ lô cho phiếu xuất', 'verbose_name_plural': 'Phân bổ lô cho phiếu xuất'},
        ),
        migrations.AlterModelOptions(
            name='ginitem',
            options={'verbose_name': 'Dòng phiếu xuất kho', 'verbose_name_plural': 'Dòng phiếu xuất kho'},
        ),
        migrations.AlterField(
            model_name='gin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='gin_no',
            field=models.CharField(editable=False, help_text='Tự sinh: GIN-YYYYMM-XXX.', max_length=30, unique=True, verbose_name='Số phiếu GIN'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='reference_no',
            field=models.CharField(blank=True, help_text='Vd PO-0001 (khi PO), hoặc mã lệnh SX/đơn bán ngoài hệ thống.', max_length=50, verbose_name='Số tham chiếu'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='reference_type',
            field=models.CharField(choices=[('PO', 'Đơn mua hàng'), ('PRODUCTION', 'Sản xuất'), ('SALES', 'Bán hàng')], max_length=20, verbose_name='Loại tham chiếu'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gins_requested', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PICKING', 'Đang soạn hàng'), ('ISSUED', 'Đã xuất'), ('CLOSED', 'Đã đóng')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gins', to='warehouse.warehouse', verbose_name='Kho'),
        ),
        migrations.AlterField(
            model_name='ginbatchallocation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gin_allocations', to='inventory.batch', verbose_name='Lô hàng'),
        ),
        migrations.AlterField(
            model_name='ginbatchallocation',
            name='gin_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='shipping.ginitem', verbose_name='Dòng phiếu GIN'),
        ),
        migrations.AlterField(
            model_name='ginbatchallocation',
            name='is_override',
            field=models.BooleanField(default=False, help_text='True nếu người dùng đổi batch khác gợi ý FIFO (FR-GIN-03).', verbose_name='Đổi batch thủ công'),
        ),
        migrations.AlterField(
            model_name='ginbatchallocation',
            name='override_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lý do đổi batch'),
        ),
        migrations.AlterField(
            model_name='ginbatchallocation',
            name='qty_allocated',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng phân bổ'),
        ),
        migrations.AlterField(
            model_name='ginitem',
            name='gin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.gin', verbose_name='Phiếu GIN'),
        ),
        migrations.AlterField(
            model_name='ginitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gin_items', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='ginitem',
            name='qty_issued',
            field=models.PositiveIntegerField(default=0, help_text='FR-GIN-05: qty thực xuất, có thể khác qty_requested.', verbose_name='Số lượng thực xuất'),
        ),
        migrations.AlterField(
            model_name='ginitem',
            name='qty_requested',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng yêu cầu'),
        ),
    ]
