# Generated by Django 5.2 on 2026-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_gin_options_alter_ginbatchallocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gin',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING_APPROVAL', 'Chờ duyệt xác nhận'), ('PICKING', 'Đang soạn hàng'), ('ISSUED', 'Đã xuất'), ('CANCELLED', 'Đã hủy'), ('CLOSED', 'Đã đóng')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
