# Generated by Django 5.2 on 2026-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_preferred_supplier'),
        ('shipping', '0003_alter_gin_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ginitem',
            constraint=models.UniqueConstraint(fields=('gin', 'product'), name='unique_product_per_gin'),
        ),
    ]
